# Based on https://www.linux.com/learn/how-build-your-own-custom-docker-images
FROM ubuntu:16.04

MAINTAINER Derek Pennycuff version 1.2

ENV DEBIAN_FRONTEND noninteractive

ENV APACHE_RUN_USER www-data
ENV APACHE_RUN_GROUP www-data
ENV APACHE_LOG_DIR /var/log/apache2
ENV APACHE_LOCK_DIR /var/lock/apache2
ENV APACHE_PID_FILE /var/run/apache2.pid

# There's no official source for php 7.1 for apt-get
# We can add a ppa / personal package archive 
# See https://launchpad.net/~ondrej/+archive/ubuntu/php/
# But that requires add-apt-repository which has to be installed 
# It is part of the package software-properties-common
# But then we get an error because the ppa author has an accent in his name
# See https://github.com/oerdnj/deb.sury.org/issues/56
# Put it all together and we get the mess below
RUN apt-get update && \
	apt-get install -y apache2 \
	language-pack-en-base && \
	export LC_ALL=en_US.UTF-8 && \
	export LANG=en_US.UTF-8 && \
	apt-get install -y software-properties-common && \
	add-apt-repository -y ppa:ondrej/php && \
	apt-get update &&  \
	apt-get -y upgrade && \
	apt-get install -y php7.1 \
	php7.1-mysql \
	libapache2-mod-php7.1 \
	php7.1-bz2 \
	php7.1-curl \
	php7.1-gd \
	imagemagick \
	php-imagick \
	php7.1-ldap \
	php7.1-mcrypt \
	php7.1-mbstring \
	php7.1-pgsql \ 
	php7.1-soap \
	php7.1-sqlite3 \
	php-xdebug \
	php7.1-xml \
	php7.1-xmlrpc \
	php7.1-zip \
	composer \
	supervisor && \
	apt-get clean && \
	rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && \
	a2enmod rewrite && \
	a2enmod expires && \
	service apache2 restart

COPY ["/etc", "/etc/"]
COPY ["/opt", "/opt/"]
COPY ["/var", "/var/"]


EXPOSE 80

CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]